""" Input system that copies files and folders from the filesystem """

import logging
import os

from pathlib import Path
from shutil import copytree, copy2

def backup(filesystem_cfg, tmp_dir):
    """ Does the backup with the configuration contained in yaml_cfg """
    logger = logging.getLogger('')

    mappings = {}
    counter = 0

    for path in filesystem_cfg['paths']:
        counter += 1

        folder = folder_name(counter)
        dest = Path(tmp_dir, folder)

        mappings[path] = folder

        logger.info("Backing up path '%s' (mapped to '%s')", path, dest.absolute().as_posix())
        if Path(path).is_file():
            os.makedirs(dest)
            copy2(path, dest)
        else:
            copytree(path, dest)

    return mappings

def folder_name(counter):
    """ Return the name of a folder generated by this plugin given a counter """
    return f"fs{counter}"
